### ISSUE TITLE
pagination should happen at 30 or more rows

### ISSUE THREAD

**Issue by ssbarnea** [bregman-arie/rhoci#14]
I think that the default pagination of 15 records is far too small for out usage and a value of 30 is likely to be much better. 

Jira also happens to have a default pagination of 30. To be hones any value starting with 30 should be ok. Even if you make it 50 or 100, I would be happy.

Having a small pagination did confused me because I got the impression that there were no other records, especially because the quick filter applies to the current page.

**Comment by bregman-arie** [comment]
When I switch to 30 I can't see all the entries in a single screen. I need to scroll, so I think we should keep it 15 or increase a little bit to 20, 25 max.

**Comment by ssbarnea** [comment]
@bregman-arie I don't have any issue with scrolling (we do it a lot with build console log) but we can also work on optimising the screen estate usage. 

Probably this is one example where is good to wait for feedback from others and find a good compromise. 

I know that you could make it configurable but it would not worth the implementation effort. Even Jenkins does not allow yet you control pagination of job searches.

Before going deeper into this, we need to decide what is the minimum supported resolution and use this as a model when comparing. I have a 13" screen which translates to 1280x800 (~1200x640 browser window). There are browser plugins that can help with resizing.

**Comment by bregman-arie** [comment]
Done
